version: '3.8'
services:

  config-mcs:
    image: config-mcs:latest
    build:
      context: .
      dockerfile: ./cofig-server/Dockerfile
    container_name: config-mcs
    ports:
      - "8888:8888"
    networks:
      - microservice-network

  discovery-mcs:
    image: discovery-mcs:latest
    build:
      context: .
      dockerfile: ./discovery/Dockerfile
    container_name: discovery-mcs
    depends_on:
      - config-mcs
    ports:
      - "8761:8761"
    networks:
      - microservice-network
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-mcs:8761/eureka/

  apigateway:
    image: apigateway:latest
    build:
      context: .
      dockerfile: ./apigateway/Dockerfile
    container_name: apigateway
    depends_on:
      - discovery-mcs
    ports:
      - "8222:8222"
    networks:
      - microservice-network
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-mcs:8761/eureka/

  identity-service:
    image: identity-service:latest
    build:
      context: .
      dockerfile: ./identityService/Dockerfile
    container_name: identity-service
    depends_on:
      - apigateway
    ports:
      - "8889:8889"
    networks:
      - microservice-network
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-mcs:8761/eureka/
      SPRING_DATA_MONGODB_URI: mongodb+srv://mykyprykhodko:QByVvtSvWepPDwHf@umbeasylearn.syb9ryg.mongodb.net/pouzivatel?retryWrites=true&w=majority

  user-mcs:
    image: user-mcs:latest
    build:
      context: .
      dockerfile: ./usermicroservice/Dockerfile
    container_name: user-mcs
    depends_on:
      - discovery-mcs
      - config-mcs
      - apigateway
    ports:
      - "8989:8989"
    networks:
      - microservice-network
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-mcs:8761/eureka/
      SPRING_DATA_MONGODB_URI: mongodb+srv://mykyprykhodko:QByVvtSvWepPDwHf@umbeasylearn.syb9ryg.mongodb.net/pouzivatel?retryWrites=true&w=majority

  subject-mcs:
    image: subject-mcs:latest
    build:
      context: .
      dockerfile: ./subjectsms/Dockerfile
    container_name: subject-mcs
    depends_on:
      - discovery-mcs
      - config-mcs
      - apigateway
    ports:
      - "8090:8090"
    networks:
      - microservice-network
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-mcs:8761/eureka/
      SPRING_DATA_MONGODB_URI: mongodb+srv://mykyprykhodko:QByVvtSvWepPDwHf@umbeasylearn.syb9ryg.mongodb.net/Predmety?retryWrites=true&w=majority
  frontend:
    build:
      context: ../UmbEasyLearn-fe
      dockerfile: Dockerfile
    container_name: angular-frontend
    ports:
      - "4200:80"  # Expose NGINX on port 4200
    networks:
      - microservice-network
networks:
  microservice-network:
    driver: bridge
