spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200/"
            allowedMethods:
              - GET
  application:
    name: apigateway
  config:
    import: optional:configserver:http://localhost:8888

