spring:
  application:
    name: identityservice

  data:
    mongodb:
      uri: mongodb+srv://mykyprykhodko:QByVvtSvWepPDwHf@umbeasylearn.syb9ryg.mongodb.net/
      database: pouzivatel
eureka:
  instance:
    hostname: discovery-mcs
  client:
    service-url:
      defaultZone: http://discovery-mcs:8761/eureka



server:
  port: 8889