spring:
  application:
    name: usermicroservice
  config:
    import: optional:configserver:http://localhost:8888
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
# Get en error with this type of solution
#  main:
#    allow-bean-definition-overriding: true
