server:
  port: 8222

spring:
  name: apigateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: subjectsms
          uri: http://localhost:8090
          predicates:
            - Path=/api/**
          filters:
            - AuthenticationFilter
        - id: usermicroservice
          uri: http://localhost:8989
          predicates:
            - Path=/users/**
        - id: identityservice
          uri: http://localhost:6666
          predicates:
            - Path=/auth/**
          filters:
            - AuthenticationFilter
#eureka:
#  client:
#    register-with-eureka: true
eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0