server:
  port: 8222

spring:
  name: apigateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PATCH
              - DELETE
              - PUT
      routes:
        - id: subjectsms
          uri: http://subject-mcs:8090
          predicates:
            - Path=/api/**
          filters:
            - AuthenticationFilter
        - id: usermicroservice
          uri: http://user-mcs:8989
          predicates:
            - Path=/users/**
          filters:
            - AuthenticationFilter
        - id: identityservice
          uri: http://identity-service:8889
          predicates:
            - Path=/auth/**
          filters:
            - AuthenticationFilter
#eureka:
#  client:
#    register-with-eureka: true
eureka:
  client:
    service-url:
      defaultZone : http://discovery-mcs:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0