server:
  port: 8222

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: subjects
          uri: http://localhost:8090
          predicates:
            - Path=/api/**
        - id: users
          uri: http://localhost:8989
          predicates:
            - Path=/users/**
eureka:
  client:
    register-with-eureka: false
