spring:
  data:
    mongodb:
#     safe connection to demo database
      uri: mongodb+srv://mykyprykhodko:QByVvtSvWepPDwHf@umbeasylearn.syb9ryg.mongodb.net/
      database: pouzivatel

eureka:
  instance:
    hostname: discovery-mcs
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka

management:
  tracing:
    sampling:
      probability: 1.0

server:
  port: 8989
