spring:
  data:
    mongodb:
      uri: "your url to database"
      database: pouzivatel

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  tracing:
    sampling:
      probability: 1.0

server:
  port: 8989
